version: "3"

services:
  listashop:
    restart: always
    build: .
    ports:
      - "6001:6001"
    volumes:
      - ./:/var/www/
    depends_on:
      - db
      - redis
  db:
    image: postgres
    restart: always
    volumes:
      - "./.docker/db:/var/lib/postgres"
    environment:
    environment:
      POSTGRES_PASSWORD: Postgres2022!
      POSTGRES_DB: listashop-api
    ports:
      - "5432:5432"
    networks:
      - postgres-network

  web:
    image: nginx
    volumes:
      - ./:/var/www
    ports:
      - "8080:80"
    build: ./.docker/nginx

    depends_on:
      - listashop

  redis:
    image: redis:alpine
    expose:
      - 6379

networks:
  postgres-network:
    driver: bridge
