version: "3"

services:
  web:
    restart: always
    build: .
    volumes:
      - ./:/var/www/
    depends_on:
      - db
      - listashop-api-redis
  db:
    image: postgres
    restart: always
    volumes:
      - "./.docker/db:/var/lib/postgres"
    environment:
      POSTGRES_PASSWORD: "Postgres2022!"
    ports:
      - "5432:5432"
    networks:
      - postgres-network

  listashop-api-nginx:
    image: nginx
    volumes:
      - ./:/var/www
    ports:
      - "8080:80"
    build: ./.docker/nginx

    depends_on:
      - web

  listashop-api-redis:
    image: redis:alpine
    expose:
      - 6379

networks:
  postgres-network:
    driver: bridge
